name: Publish to PyPI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: Determine version
      id: get_version
      run: |
        if [ "${{ github.event_name }}" = "push" ]; then
          REF_NAME="${GITHUB_REF#refs/tags/}"
          VERSION="${REF_NAME#v}"
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Using version from tag: $VERSION"
        else
          VERSION=$(grep "version = " pyproject.toml | head -1 | cut -d'"' -f2)
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Using version from pyproject.toml: $VERSION"
        fi
        
    - name: Build package
      run: |
        python -m build
        
    - name: Check distribution
      run: |
        twine check dist/*
        
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*
