name: Publish to Test PyPI

on:
  push:
    branches:
      - develop
      - test-release
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and Publish to Test PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: Get current version and add dev suffix
      id: version
      run: |
        BASE_VERSION=$(grep "version = " pyproject.toml | head -1 | cut -d'"' -f2)
        DEV_VERSION="${BASE_VERSION}.dev$(date +%Y%m%d%H%M%S)"
        echo "DEV_VERSION=$DEV_VERSION" >> $GITHUB_OUTPUT
        echo "Using dev version: $DEV_VERSION"
        
    - name: Update version to dev version
      run: |
        VERSION=${{ steps.version.outputs.DEV_VERSION }}
        sed -i "s/version = \".*\"/version = \"$VERSION\"/" pyproject.toml
        sed -i "s/version=\".*\"/version=\"$VERSION\"/" setup.py
        sed -i "s/__version__ = \".*\"/__version__ = \"$VERSION\"/" chessboard_generator/__init__.py
        
    - name: Build package
      run: |
        python -m build
        
    - name: Check distribution
      run: |
        twine check dist/*
        
    - name: Publish to Test PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        twine upload --repository testpypi dist/*
